### ISSUE TITLE
Win 7 x64 GeoSense sensor GetTimestamp failure

### ISSUE THREAD

**Issue by pwrigshi** [contre/Windows-API-Code-Pack-1.1#18]
I installed GeoSense sensor and able to see it in sensor list, but the code still throws an error

Stacktrace:
Microsoft.WindowsAPICodePack.Sensors.SensorPlatformException: No sensors found.  Are any  sensor drivers installed?
at Microsoft.WindowsAPICodePack.Sensors.SensorManager.GetSensorsByCategoryId(Guid category)
at Microsoft.WindowsAPICodePack.Sensors.SensorManager.GetAllSensors()
at GetLocationEvent.Program.Main(string[] args) in ...

all code is this:
```
SensorList<Sensor> list = SensorManager.GetAllSensors();

  foreach (var item in list)
  {
         item.UpdateData();
         Console.WriteLine(item.FriendlyName);
   }
```

Installed same sensor on Win 10, but could not test it, as code above always throws Interop exceptions on UpdateData method
I will try to check it myself, but I am newbie in desktop development.

**Comment by pwrigshi** [comment]
ok, this issue does not refers to this project.
this link helped: https://arstechnica.com/civis/viewtopic.php?f=15&t=1136778
> Yes; go into device manager and disable then re-enable the device

Still, could you provide a solution for now both Win 7 and Win 10 
Stack trace:
```
System.Runtime.InteropServices.COMExceptiom: Catastrophic Failure (Exception from HRESULT: 0x8000FFFF (E_UNEXPECTED))
at Microsoft.WindowsAPI.CodePack.Sensors.ISensorDataReport.GetTimestamp(SystemTime& timeStamp)
at Microsoft.WindowsAPI.CodePack.Sensors.SensorReport.FromNativeReport(Sensor originator, ISensorDataReport iReport)
at Microsoft.WindowsAPI.CodePack.Sensors.Sensor.InternalUpdateData()
at Microsoft.WindowsAPI.CodePack.Sensors.Sensor.UpdateData()
at GetLocationEvent.Program.Main(string[] args) in ...
```
