### ISSUE TITLE
Cannot run on machine with FIPS mode enabled

### ISSUE THREAD

**Issue by johnthagen** [contre/Windows-API-Code-Pack-1.1#55]
On a Windows system with FIPS enforcement enabled, I get the following stacktrace:

```
System.TypeInitializationException: The type initializer for 'Microsoft.WindowsAPICodePack.Shell.ShellObject' threw an exception. ---> System.InvalidOperationException: This implementation is not part of the Windows Platform FIPS validated cryptographic algorithms.
   at System.Security.Cryptography.MD5CryptoServiceProvider..ctor()
   at Microsoft.WindowsAPICodePack.Shell.ShellObject..cctor()
   --- End of inner exception stack trace ---
   at Microsoft.WindowsAPICodePack.Shell.ShellObject.op_Inequality(ShellObject leftShellObject, ShellObject rightShellObject)
   at Microsoft.WindowsAPICodePack.Dialogs.CommonFileDialog.ApplyNativeSettings(IFileDialog dialog)
   at Microsoft.WindowsAPICodePack.Dialogs.CommonFileDialog.ShowDialog()
   at PcbDrImporter.ProjectGeneration.ProjectGeneration.SelectProjectPath()
   at PcbDrImporter.ProjectGeneration.ProjectGeneration.Main()
   at PcbDrImporter.Layout.ImportLayout.Import()
   at CSharpPlugin.PluginServerModule.ImportLayoutCommand(IServerDocumentView view, String& parameters)
   at DXP.CommandLauncher.LaunchCommandImpl(String argCommandName, String& argParameters, IServerDocumentView argContext)
```

Code:

```c#
var dialog = new CommonOpenFileDialog();
dialog.IsFolderPicker = true;
dialog.InitialDirectory = Environment.GetFolderPath(Environment.SpecialFolder.UserProfile);
dialog.showDialog()
```

### Environment

- Windows 10 with FIPS mode crypto enforcement enabled
- C# 7.3
- .NET Framework 4.8
- `<PackageReference Include="Microsoft-WindowsAPICodePack-Shell" Version="1.1.4"/>` 

### Solution

Can a newer hash crypto service provider be used, such as SHA-256?

**Comment by johnthagen** [comment]
Looks like this may be a duplicate of

- #42

**Comment by johnthagen** [comment]
This has been fixed in the new active fork:

- [Microsoft-WindowsAPICodePack-6.0](https://github.com/samypr100/Windows-API-Code-Pack-1.1)
